In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 

In [3]:
a=2
b=3
a
b

2

3

In [5]:
import numpy as np
import time

size = 1_000_000  # 1 million

list1 = list(range(size))
list2 = list(range(size))
# [1,2,3,4....]
# [1,2,3,4....]
start = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print(f"Python list time: {end - start:.5f} seconds")

array1 = np.arange(size)
array2 = np.arange(size)
start = time.time()
result_array = array1 + array2
end = time.time()
print(f"NumPy array time: {end - start:.5f} seconds")

Python list time: 0.05226 seconds
NumPy array time: 0.00200 seconds


In [ ]:
#creating arrays

In [23]:
import numpy as np
l=list(range(10))
l
np.array(l)
l.append('y')
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'y']

In [15]:

arr=np.array([[1,2,3],[3,4,5]])
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [25]:
arr.shape
arr.ndim
arr.size
arr.dtype

(2, 3)

2

6

dtype('int64')

In [29]:
# start,end,step
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.linspace(1,11,10)
np.linspace(1,11,10).dtype
np.linspace(1,11,10).astype(int)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

dtype('float64')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
a=np.arange(10,20)
a
a.shape
a=a.reshape((5,2))
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

(10,)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [63]:
a.T

array([[10, 12, 14, 16, 18],
       [11, 13, 15, 17, 19]])

In [67]:
np.random.random((2,3))

array([[0.60177184, 0.65963852, 0.80264099],
       [0.61242432, 0.06586587, 0.82820748]])

In [69]:
np.random.randint(1,10,(2,3))

array([[8, 8, 7],
       [6, 9, 1]])

In [73]:
arr=np.random.randint(10,20,(5,5))

In [109]:
np.random.seed(45)
np.random.randint(10,20,(5,5))

array([[13, 10, 15, 13, 14],
       [19, 18, 11, 15, 19],
       [16, 18, 17, 18, 15],
       [12, 18, 11, 16, 14],
       [18, 14, 16, 14, 19]])

In [117]:
l
l[1:4]
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'y']

[1, 2, 3]

array([[11, 15, 13, 16, 18],
       [15, 19, 12, 11, 10],
       [11, 16, 15, 17, 11],
       [15, 18, 19, 12, 15],
       [10, 17, 16, 11, 16]])

In [121]:
# arr[#dim1,#dim2]
arr[::2,::2]

array([[11, 13, 18],
       [11, 15, 11],
       [10, 16, 16]])

# Vectorization

In [130]:
arr
arr+3
arr-4
arr+arr
arr**2
arr*arr

array([[11, 15, 13, 16, 18],
       [15, 19, 12, 11, 10],
       [11, 16, 15, 17, 11],
       [15, 18, 19, 12, 15],
       [10, 17, 16, 11, 16]])

array([[14, 18, 16, 19, 21],
       [18, 22, 15, 14, 13],
       [14, 19, 18, 20, 14],
       [18, 21, 22, 15, 18],
       [13, 20, 19, 14, 19]])

array([[ 7, 11,  9, 12, 14],
       [11, 15,  8,  7,  6],
       [ 7, 12, 11, 13,  7],
       [11, 14, 15,  8, 11],
       [ 6, 13, 12,  7, 12]])

array([[22, 30, 26, 32, 36],
       [30, 38, 24, 22, 20],
       [22, 32, 30, 34, 22],
       [30, 36, 38, 24, 30],
       [20, 34, 32, 22, 32]])

array([[121, 225, 169, 256, 324],
       [225, 361, 144, 121, 100],
       [121, 256, 225, 289, 121],
       [225, 324, 361, 144, 225],
       [100, 289, 256, 121, 256]])

In [138]:
a1=np.random.randint(10,20,(5,1))
a1
a2=np.random.randint(10,20,(1,5))
a2

array([[10],
       [19],
       [12],
       [16],
       [17]])

array([[10, 10, 12, 19, 12]])

In [140]:
arr+a1
arr+a2

array([[21, 25, 23, 26, 28],
       [34, 38, 31, 30, 29],
       [23, 28, 27, 29, 23],
       [31, 34, 35, 28, 31],
       [27, 34, 33, 28, 33]])

array([[21, 25, 25, 35, 30],
       [25, 29, 24, 30, 22],
       [21, 26, 27, 36, 23],
       [25, 28, 31, 31, 27],
       [20, 27, 28, 30, 28]])

In [146]:
arr
arr.mean()
arr.std()

array([[11, 15, 13, 16, 18],
       [15, 19, 12, 11, 10],
       [11, 16, 15, 17, 11],
       [15, 18, 19, 12, 15],
       [10, 17, 16, 11, 16]])

14.36

2.854890540808877

In [150]:
arr.mean(axis=0)
arr.mean(axis=1)

array([12.4, 17. , 15. , 13.4, 14. ])

array([14.6, 13.4, 14. , 15.8, 14. ])

In [154]:
arr.sort(axis=1)
arr

array([[11, 13, 15, 16, 18],
       [10, 11, 12, 15, 19],
       [11, 11, 15, 16, 17],
       [12, 15, 15, 18, 19],
       [10, 11, 16, 16, 17]])

In [158]:
arr@arr
np.matmul(arr,arr)

array([[ 788,  889, 1074, 1187, 1310],
       [ 722,  817,  991, 1091, 1201],
       [ 758,  856, 1034, 1141, 1255],
       [ 853,  965, 1159, 1285, 1421],
       [ 758,  854, 1034, 1141, 1254]])

array([[ 788,  889, 1074, 1187, 1310],
       [ 722,  817,  991, 1091, 1201],
       [ 758,  856, 1034, 1141, 1255],
       [ 853,  965, 1159, 1285, 1421],
       [ 758,  854, 1034, 1141, 1254]])

In [160]:
np.linalg.det(arr)

-305.00000000000034

In [162]:
np.linalg.norm(2)

2.0

In [166]:
arr
arr>15

array([[11, 13, 15, 16, 18],
       [10, 11, 12, 15, 19],
       [11, 11, 15, 16, 17],
       [12, 15, 15, 18, 19],
       [10, 11, 16, 16, 17]])

array([[False, False, False,  True,  True],
       [False, False, False, False,  True],
       [False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [False, False,  True,  True,  True]])

In [168]:
arr[arr>15]

array([16, 18, 19, 16, 17, 18, 19, 16, 16, 17])

In [216]:
arr=np.random.randint(10,20,(5,5))
arr

array([[13, 15, 15, 17, 11],
       [10, 12, 11, 19, 12],
       [13, 19, 16, 13, 16],
       [11, 19, 11, 17, 14],
       [10, 12, 11, 11, 14]])

In [206]:
w=arr[::2]
w
w[:2]=3
w
arr


array([[ 3,  3,  3,  3,  3],
       [ 3,  3,  3,  3,  3],
       [17, 14, 19, 19, 19]])

array([[ 3,  3,  3,  3,  3],
       [ 3,  3,  3,  3,  3],
       [17, 14, 19, 19, 19]])

array([[ 3,  3,  3,  3,  3],
       [18, 18, 10, 16, 17],
       [ 3,  3,  3,  3,  3],
       [15, 19, 13, 12, 17],
       [17, 14, 19, 19, 19]])

In [214]:
w=arr[::2].copy()
w
w[:2]=3
w
arr

array([[19, 17, 12, 17, 19],
       [16, 12, 17, 17, 16],
       [14, 19, 13, 15, 17]])

array([[ 3,  3,  3,  3,  3],
       [ 3,  3,  3,  3,  3],
       [14, 19, 13, 15, 17]])

array([[19, 17, 12, 17, 19],
       [14, 15, 17, 19, 17],
       [16, 12, 17, 17, 16],
       [16, 13, 16, 10, 17],
       [14, 19, 13, 15, 17]])

In [218]:
arr[~(arr>15)]=-1
arr

array([[-1, -1, -1, 17, -1],
       [-1, -1, -1, 19, -1],
       [-1, 19, 16, -1, 16],
       [-1, 19, -1, 17, -1],
       [-1, -1, -1, -1, -1]])